[project]
name = "remixtree"
dynamic = ["version"]
description = "remake scratch's remix tree feature #BringBackRemixTrees"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.9"
license = { text = "MIT" }
dependencies = [
  "aiohttp",
  "rich",
]
authors = [
  { name = "Alastrantia", email = "example@email.com" },
]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Build Tools",
  "Topic :: Education",
]

[project.urls]
Homepage = "https://github.com/Alastrantia/scratch-remixtree"
BugTracker = "https://github.com/Alastrantia/scratch-remixtree/issues"

[project.scripts]
remixtree = "remixtree.main:main_sync"

[build-system]
requires = ["setuptools>=61.0", "wheel", "setuptools-scm>=8.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
# this shoouuuuuld get the version from git tagging

[tool.setuptools.packages]
find = { where = ["."], include = ["remixtree*", "remixtree_cli*"], exclude = ["demos*", "tests*"] }